export default {
  getData: () => {
    return [
      {
        id: 1,
        company_id: 1,
        location_id: 2,
        order_date: "2023-03-21T11:25:34Z",
        tax: null,
        status: "UNFULFILLED",
        updated: null,
        name: "Cass Veldens",
        phone: "563-147-2560",
        email: "cveldens0@google.cn",
        label: "Boyle, Schuster and Anderson",
        address1: "7139 Vermont Way",
      },
      {
        id: 2,
        company_id: 2,
        location_id: 3,
        order_date: "2023-03-20T08:15:22Z",
        tax: null,
        status: "UNFULFILLED",
        updated: null,
        name: "Michel Furber",
        phone: "352-819-6920",
        email: "mfurber1@csmonitor.com",
        label: "Yundt-Mertz",
        address1: "3 Lighthouse Bay Place",
      },
      {
        id: 3,
        company_id: 3,
        location_id: 5,
        order_date: "2022-06-24T23:27:16Z",
        tax: null,
        status: "UNFULFILLED",
        updated: null,
        name: "Malvina Hause",
        phone: "180-490-6488",
        email: "mhause2@people.com.cn",
        label: "Donnelly-Sipes",
        address1: "48624 Melody Way",
      },
      {
        id: 4,
        company_id: 4,
        location_id: 4,
        order_date: "2022-09-26T13:19:27Z",
        tax: null,
        status: "UNFULFILLED",
        updated: null,
        name: "Rebecca Verriour",
        phone: "516-158-2326",
        email: "rverriour3@wix.com",
        label: "Littel and Sons",
        address1: "2543 Nova Place",
      },
      {
        id: 5,
        company_id: 5,
        location_id: 4,
        order_date: "2022-09-30T10:05:23Z",
        tax: null,
        status: "RECEIVED",
        updated: null,
        name: "Clemens Tailby",
        phone: "324-772-9243",
        email: "ctailby4@ocn.ne.jp",
        label: "Littel and Sons",
        address1: "2543 Nova Place",
      },
    ];
  },
};
