import { Appsmith } from "./Appsmith";

export enum DatasourceType {
    RESTAPI = "RESTAPI",
    MYSQL = "MYSQL",
    POSTGRES = "POSTGRES",
}

export class Datasource extends Appsmith {
  name: string;
  type: DatasourceType;
  pluginId: string;
  messages: Array<string> = [];
  isAutoGenerated: boolean = false;
  deleted: boolean = false;
  gitSyncId: string = null;

  constructor(name: string, type: DatasourceType) {
    super(name);
    this.name = name;
    this.type = type;
  }

  setPluginId(pluginId: string) {
    this.pluginId = pluginId;
    return this;
  }
}
